name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: Print latest_commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
  build:
    runs-on: ubuntu-latest
    name: Build
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout tool
        uses: actions/checkout@v4
        with:
          repository: Illidanz/NarutoRPG2Translation
          token: ${{ secrets.GH_PAT }}
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Checkout data
        uses: actions/checkout@v4
        with:
          path: NarutoRPG2Data
      - name: Download data
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url: ${{ secrets.URL_DATA }}
      - name: Extract data
        run: |
          7z x naruto.7z
          mv en1.sdat NarutoRPG2Data/sound/en1.sdat
          mv en2.sdat NarutoRPG2Data/sound/en2.sdat
      - name: Install dependencies
        run: pipenv --python 3.12 sync
      - name: Extract
        run: pipenv run python tool.py extract --rom --img
      - name: Repack sub
        run: pipenv run python tool.py repack
      - name: Rename sub
        run: mv NarutoRPG2Data/patch.xdelta NarutoRPG2Data/patch_sub.xdelta
      - name: Upload sub patch
        uses: actions/upload-artifact@v4
        with:
          name: patch_sub.xdelta
          path: NarutoRPG2Data/patch_sub.xdelta
          retention-days: 7
      - name: Repack dub
        run: pipenv run python tool.py repack --snd
      - name: Rename dub
        run: mv NarutoRPG2Data/patch.xdelta NarutoRPG2Data/patch_dub.xdelta
      - name: Upload dub patch
        uses: actions/upload-artifact@v4
        with:
          name: patch_dub.xdelta
          path: NarutoRPG2Data/patch_dub.xdelta
          retention-days: 7
      - name: Check sub patch existence
        id: check_patch_sub
        uses: andstor/file-existence-action@v3
        with:
          files: "NarutoRPG2Data/patch_sub.xdelta"
      - name: Check dub patch existence
        id: check_patch_dub
        uses: andstor/file-existence-action@v3
        with:
          files: "NarutoRPG2Data/patch_dub.xdelta"
      - name: Webhook sub
        if: ${{ steps.check_patch_sub.outputs.files_exists == 'true' }}
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "A new sub nightly patch is available for testing! ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "AGTTBot"
          avatar-url: "https://avatars.githubusercontent.com/u/123242276?v=4"
          filename: "NarutoRPG2Data/patch_sub.xdelta"
      - name: Webhook dub
        if: ${{ steps.check_patch_dub.outputs.files_exists == 'true' }}
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "A new dub nightly patch is available for testing! ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          username: "AGTTBot"
          avatar-url: "https://avatars.githubusercontent.com/u/123242276?v=4"
          filename: "NarutoRPG2Data/patch_dub.xdelta"
